[package]
name = "tutorial1-window"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "tutorial1-window"
path = "src/main.rs"

[dependencies]
winit = "0.25.0"
env_logger = "0.8.3"
