[package]
name = "macos-window"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
cocoa = "0.24.0"
core-graphics = "0.22.2"
objc = "0.2.7"

[dependencies.neon]
version = "0.8"
default-features = false
features = ["napi-6"]
